spring.application.name=school
#server.port=9000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/school_db?createDatabaseIfNotExist=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Session Configuration
# spring.session.store-type=jdbc
# spring.session.jdbc.initialize-schema=always
# spring.session.jdbc.platform=mysql
# spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-mysql.sql
spring.session.cookie.same-site=none
spring.session.cookie.secure=true
