services:
  mysql-db:
    image: mysql:8.0
    container_name: school-mysql
    environment:
      MYSQL_DATABASE: school_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./school-backend
    container_name: school-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/school_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword

  frontend:
    build: ./my-school-ui
    container_name: school-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend